In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [13]:
df = pd.read_csv('../final5.csv')

In [14]:
df.head()

,index,verbatimScientificName,stateProvince,individualCount,decimalLatitude,decimalLongitude,eventDate,avg_rad,cf_cvg,NDVI_raw,LandCover_Class,elevation_meters,BCSMASS,DUEXTT25,DUSMASS,OCSMASS,SO2SMASS,SO4SMASS,SSSMASS,TOTEXTTAU,TOTSCATAU,temp_mean,temp_max,temp_min,rainfall,wind_mean,humid_mean,shortwave_radiation,lka_general_2020
0,0,Anarhynchus alexandrinus,Mannar,8.0,9.058512,79.855020,2021-01-06,0.66,5.0,3792.0,10,0,5.794512e-10,0.001600,1.548033e-09,2.780749e-09,1.643020e-10,3.372161e-09,3.725563e-08,0.175115,0.165737,26.58,28.52,24.74,15.17,1.31,85.53,17.65,2.805795
1,1,Columba livia,Colombo,31.0,6.927894,79.865005,2024-09-24,25.40,1.0,5692.0,13,12,3.096564e-10,0.021307,1.578878e-08,1.537093e-09,4.319662e-09,1.169898e-09,5.924096e-08,0.191869,0.184795,27.52,29.55,26.03,2.63,5.50,84.41,20.77,39.099075
2,2,Hirundo rustica,Colombo,10.0,6.866285,79.931440,2024-12-23,10.16,7.0,7045.0,13,5,9.678071e-10,0.001877,2.117789e-09,4.676763e-09,4.725881e-09,4.424376e-09,3.249729e-08,0.198127,0.187366,26.21,28.84,24.10,0.25,2.51,84.30,20.49,8.917330
3,3,Geokichla spiloptera,Matale,1.0,7.401229,80.690730,2024-09-13,1.13,1.0,9506.0,8,876,2.822976e-10,0.020004,1.525811e-08,1.535989e-09,2.551352e-09,1.286736e-09,3.795434e-08,0.162928,0.156176,27.29,32.96,23.45,0.17,4.11,76.89,22.42,11.386136
4,4,Himantopus himantopus,Puttalam,6.0,8.154166,79.736084,2024-11-28,0.79,2.0,NaN,11,2,8.410959e-10,0.001956,1.985992e-09,4.197754e-09,1.223400e-09,4.910509e-09,4.148581e-08,0.213164,0.203239,25.86,27.55,24.85,0.99,6.15,84.07,8.78,3.522320

In [15]:
df.columns

Index(['index', 'verbatimScientificName', 'stateProvince', 'individualCount',
       'decimalLatitude', 'decimalLongitude', 'eventDate', 'avg_rad', 'cf_cvg',
       'NDVI_raw', 'LandCover_Class', 'elevation_meters', 'BCSMASS',
       'DUEXTT25', 'DUSMASS', 'OCSMASS', 'SO2SMASS', 'SO4SMASS', 'SSSMASS',
       'TOTEXTTAU', 'TOTSCATAU', 'temp_mean', 'temp_max', 'temp_min',
       'rainfall', 'wind_mean', 'humid_mean', 'shortwave_radiation',
       'lka_general_2020'],
      dtype='str')

In [ ]:
df["NDVI"] = pd.to_numeric(df["NDVI_raw"], errors="coerce") / 10000
df = df.dropna(subset=["NDVI", "lka_general_2020"])
df = df[(df["cf_cvg"] != 0) & (df["cf_cvg"] != 1)]
df = df.drop(columns=["TOTSCATAU", "DUEXTT25", "OCSMASS", "temp_max" ,"temp_min", "cf_cvg"])

In [ ]:
# Rename columns for clarity
df = df.rename(columns={
    'BCSMASS': 'Carbon_Mass',
    'DUSMASS': 'Dust_Mass',
    'SO2SMASS': 'SO2_Mass',
    'SO4SMASS': 'Sulfate_Mass',
    'SSSMASS': 'Sea_Salt_Mass',
    'TOTEXTTAU': 'Total_Aerosol_Extinction'
}) # type: ignore

0

In [20]:
df.head()

,index,verbatimScientificName,stateProvince,individualCount,decimalLatitude,decimalLongitude,eventDate,avg_rad,NDVI_raw,LandCover_Class,elevation_meters,Carbon_Mass,Dust_Mass,SO2_Mass,Sulfate_Mass,Sea_Salt_Mass,Total_Aerosol_Extinction,temp_mean,rainfall,wind_mean,humid_mean,shortwave_radiation,lka_general_2020,NDVI
0,0,Anarhynchus alexandrinus,Mannar,8.0,9.058512,79.85502,2021-01-06,0.66,3792.0,10,0,5.794512e-10,1.548033e-09,1.643020e-10,3.372161e-09,3.725563e-08,0.175115,26.58,15.17,1.31,85.53,17.65,2.805795,0.3792
2,2,Hirundo rustica,Colombo,10.0,6.866285,79.93144,2024-12-23,10.16,7045.0,13,5,9.678071e-10,2.117789e-09,4.725881e-09,4.424376e-09,3.249729e-08,0.198127,26.21,0.25,2.51,84.30,20.49,8.917330,0.7045
5,6,Corvus macrorhynchos,Matara,2.0,5.983496,80.52548,2024-10-12,1.26,6989.0,10,5,2.578500e-10,3.088314e-09,1.444164e-09,7.456183e-10,5.362027e-08,0.131458,26.91,14.47,5.18,83.81,15.67,2.768103,0.6989
6,7,Dicrurus caerulescens,Matale,1.0,7.969125,80.75477,2021-11-20,0.37,8543.0,8,194,4.901116e-10,6.928122e-09,1.376567e-09,1.612494e-09,3.017664e-08,0.123156,25.30,2.54,2.98,89.54,21.99,3.339740,0.8543
7,8,Threskiornis melanocephalus,Jaffna,30.0,9.637712,79.95190,2019-03-25,0.52,4000.0,10,2,4.829281e-10,2.295270e-08,3.812554e-10,2.737918e-09,3.224930e-08,0.220155,29.67,0.00,4.65,63.33,24.53,3.209018,0.4000

In [ ]:
# Save the final DataFrame as file6.csv
df.to_csv('../file6.csv', index=False)