In [1]:
import pandas as pd

In [2]:
path = '0001215-260221153910048.csv' #Original Dataset from eBird site
df = pd.read_csv(path, sep='\t')

In [3]:
pd.set_option('display.max_columns', None)
df.head()

,gbifID,datasetKey,occurrenceID,kingdom,phylum,class,order,family,genus,species,infraspecificEpithet,taxonRank,scientificName,verbatimScientificName,verbatimScientificNameAuthorship,countryCode,locality,stateProvince,occurrenceStatus,individualCount,publishingOrgKey,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,coordinatePrecision,elevation,elevationAccuracy,depth,depthAccuracy,eventDate,day,month,year,taxonKey,speciesKey,basisOfRecord,institutionCode,collectionCode,catalogNumber,recordNumber,identifiedBy,dateIdentified,license,rightsHolder,recordedBy,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue
0,3621351660,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS1045775508,Animalia,Chordata,Aves,Charadriiformes,Charadriidae,Charadrius,Charadrius alexandrinus,NaN,SPECIES,Anarhynchus alexandrinus,Anarhynchus alexandrinus,NaN,LK,Mannar Island--Pudukudyirrippu Lagoon,Mannar,PRESENT,8.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,9.058512,79.855020,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-06,6,1,2021,9372299,2480311.0,HUMAN_OBSERVATION,CLO,EBIRD,OBS1045775508,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr1081864,NaN,NaN,2025-11-07T05:59:29.578Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_CONCE...
1,5578422728,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS2485882127,Animalia,Chordata,Aves,Columbiformes,Columbidae,Columba,Columba livia,NaN,SPECIES,"Columba livia J.F.Gmelin, 1789",Columba livia,NaN,LK,"Maradana Railway Station (6.928, 79.865)",Colombo,PRESENT,31.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,6.927894,79.865005,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-24,24,9,2024,2495414,2495414.0,HUMAN_OBSERVATION,CLO,EBIRD,OBS2485882127,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr225081,NaN,NaN,2025-11-07T06:06:57.304Z,NaN,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
2,5394140911,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS2717750892,Animalia,Chordata,Aves,Passeriformes,Hirundinidae,Hirundo,Hirundo rustica,NaN,SPECIES,"Hirundo rustica Linnaeus, 1758",Hirundo rustica,NaN,LK,Kimbulawala,Colombo,PRESENT,10.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,6.866285,79.931440,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-23,23,12,2024,9515886,9515886.0,HUMAN_OBSERVATION,CLO,EBIRD,OBS2717750892,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr2852485,NaN,NaN,2025-11-07T06:06:32.940Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_CONCE...
3,5412795688,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS2458409511,Animalia,Chordata,Aves,Passeriformes,Turdidae,Geokichla,Geokichla spiloptera,NaN,SPECIES,"Geokichla spiloptera (Blyth, 1847)",Geokichla spiloptera,NaN,LK,"Hunas Falls Hotel, Central Province, LK (7.401...",Matale,PRESENT,1.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,7.401229,80.690730,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-13,13,9,2024,6100891,6100891.0,HUMAN_OBSERVATION,CLO,EBIRD,OBS2458409511,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr1470679,NaN,NaN,2025-11-07T06:05:32.192Z,NaN,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
4,5446065256,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS2652427002,Animalia,Chordata,Aves,Charadriiformes,Recurvirostridae,Himantopus,Himantopus himantopus,NaN,SPECIES,"Himantopus himantopus (Linnaeus, 1758)",Himantopus himantopus,NaN,LK,Nachukalli Musalpitiya Wetlands Kalpitiya,Puttalam,PRESENT,6.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,8.154166,79.736084,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-28,28,11,2024,5229126,5229126.0,HUMAN_OBSERVATION,CLO,EBIRD,OBS2652427002,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr1806178,NaN,NaN,2025-11-07T06:05:14.594Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_CONCE...

In [4]:
df.isna().sum()

gbifID                                    0
datasetKey                                0
occurrenceID                              0
kingdom                                   0
phylum                                    0
class                                     0
order                                 24369
family                                24369
genus                                     0
species                               75334
infraspecificEpithet                2382899
taxonRank                                 0
scientificName                            0
verbatimScientificName                    0
verbatimScientificNameAuthorship    2382899
countryCode                               0
locality                                  0
stateProvince                             0
occurrenceStatus                          0
individualCount                      289862
publishingOrgKey                          0
decimalLatitude                           0
decimalLongitude                          0
coordinateUncertaintyInMeters       2382899
coordinatePrecision                 2382899
elevation                           2382899
elevationAccuracy                   2382899
depth                               2382899
depthAccuracy                       2382899
eventDate                                 0
day                                       0
month                                     0
year                                      0
taxonKey                                  0
speciesKey                            75334
basisOfRecord                             0
institutionCode                           0
collectionCode                            0
catalogNumber                             0
recordNumber                        2382899
identifiedBy                        2382899
dateIdentified                      2382899
license                                   0
rightsHolder                        2382899
recordedBy                                0
typeStatus                          2382899
establishmentMeans                  2382899
lastInterpreted                           0
mediaType                           2382899
issue                                     0
dtype: int64

In [5]:
#Drop consttant columns
x = df.nunique()
df_cleaned = df.drop(columns=[i for i in df.columns if x[i] <= 1])

In [6]:
#Drop redundent columns
df_cleaned = df_cleaned.drop(columns=['day', 'month', 'year'])

In [7]:
#Drop unrelated columns
df_cleaned = df_cleaned.drop(columns=['gbifID', 'occurrenceID', 'locality',
                                       'catalogNumber', 'lastInterpreted', 'collectionCode', 'issue',
                                       'order', 'family', 'genus', 'scientificName', 'taxonRank'
                                        ,'taxonKey', 'speciesKey', 'recordedBy'])

In [8]:
df_cleaned.head()

,species,verbatimScientificName,stateProvince,individualCount,decimalLatitude,decimalLongitude,eventDate
0,Charadrius alexandrinus,Anarhynchus alexandrinus,Mannar,8.0,9.058512,79.855020,2021-01-06
1,Columba livia,Columba livia,Colombo,31.0,6.927894,79.865005,2024-09-24
2,Hirundo rustica,Hirundo rustica,Colombo,10.0,6.866285,79.931440,2024-12-23
3,Geokichla spiloptera,Geokichla spiloptera,Matale,1.0,7.401229,80.690730,2024-09-13
4,Himantopus himantopus,Himantopus himantopus,Puttalam,6.0,8.154166,79.736084,2024-11-28

In [9]:
#Merge with dataset containing stalite image based ratience and cloud coverage dataset
df1 = pd.read_csv('TRUSTED_VIIRS_ALAN_Data.csv')

df2 = df_cleaned.copy()

if 'index' not in df2.columns:
    df2 = df2.reset_index()

print("2. Merging datasets together...")
final_df = pd.merge(df2, df1, on='index', how='left')

print("Success! Your master dataset is completely built and ready for ecological analysis.")

2. Merging datasets together...
Success! Your master dataset is completely built and ready for ecological analysis.

In [10]:
pd.set_option('display.max_columns', None)
final_df.head()

,index,species,verbatimScientificName,stateProvince,individualCount,decimalLatitude,decimalLongitude,eventDate,avg_rad,cf_cvg
0,0,Charadrius alexandrinus,Anarhynchus alexandrinus,Mannar,8.0,9.058512,79.855020,2021-01-06,0.66,5.0
1,1,Columba livia,Columba livia,Colombo,31.0,6.927894,79.865005,2024-09-24,25.40,1.0
2,2,Hirundo rustica,Hirundo rustica,Colombo,10.0,6.866285,79.931440,2024-12-23,10.16,7.0
3,3,Geokichla spiloptera,Geokichla spiloptera,Matale,1.0,7.401229,80.690730,2024-09-13,1.13,1.0
4,4,Himantopus himantopus,Himantopus himantopus,Puttalam,6.0,8.154166,79.736084,2024-11-28,0.79,2.0

In [11]:
final_df = final_df.drop(columns=['species'])
final_df.head()

,index,verbatimScientificName,stateProvince,individualCount,decimalLatitude,decimalLongitude,eventDate,avg_rad,cf_cvg
0,0,Anarhynchus alexandrinus,Mannar,8.0,9.058512,79.855020,2021-01-06,0.66,5.0
1,1,Columba livia,Colombo,31.0,6.927894,79.865005,2024-09-24,25.40,1.0
2,2,Hirundo rustica,Colombo,10.0,6.866285,79.931440,2024-12-23,10.16,7.0
3,3,Geokichla spiloptera,Matale,1.0,7.401229,80.690730,2024-09-13,1.13,1.0
4,4,Himantopus himantopus,Puttalam,6.0,8.154166,79.736084,2024-11-28,0.79,2.0

In [12]:
final_df.shape

(2382899, 9)

In [13]:
final_df.isna().sum()

index                          0
verbatimScientificName         0
stateProvince                  0
individualCount           289862
decimalLatitude                0
decimalLongitude               0
eventDate                      0
avg_rad                   156469
cf_cvg                    156469
dtype: int64

In [17]:
#Remove any row before 2014 or that have null individual count

incoplete_rows = final_df[(final_df['individualCount'].isna()) | (final_df['cf_cvg'].isna()) | \
                               (final_df['avg_rad'].isna())]

In [18]:
final_df = final_df.drop(index=incoplete_rows.index)

In [19]:
final_df.shape

(1999208, 9)

In [20]:
#Check naming errors in 2 columns

idx = []
for i, row in df.iterrows():
    if row['verbatimScientificName'].lower() not in row['scientificName'].lower():
        idx.append(i)

In [21]:
x = df.loc[idx, ['verbatimScientificName', 'scientificName']]

In [22]:
#Check different unique combinations
x.drop_duplicates()

       verbatimScientificName                          scientificName
56            Ardea coromanda                    Ardea Linnaeus, 1758
85           Tachyspiza badia                   Tachyspiza Kaup, 1844
89         Tachyspiza virgata                   Tachyspiza Kaup, 1844
142       Plocealauda affinis                  Plocealauda Gray, 1844
185     Anarhynchus atrifrons        Anarhynchus Quoy & Gaimard, 1832
372       Pachyglossa vincens               Pachyglossa Hodgson, 1843
430          Thinornis dubius                Thinornis G.R.Gray, 1844
484         Botaurus sinensis                 Botaurus Stephens, 1819
950      Botaurus cinnamomeus                 Botaurus Stephens, 1819
1189    Lophospiza trivirgata                   Lophospiza Kaup, 1844
1193    Ictinaetus malaiensis  Ictinaetus malayensis (Temminck, 1822)
1743         Copsychus leggei                  Copsychus Wagler, 1827
2783       Pachyglossa agilis               Pachyglossa Hodgson, 1843
3572     Botaurus flavicollis                 Botaurus Stephens, 1819
749022    Botaurus eurhythmus                 Botaurus Stephens, 1819

In [24]:
#Fix only naming error
final_df.loc[final_df['verbatimScientificName'] == 'Ictinaetus malaiensis'] = 'Ictinaetus malayensis'

In [26]:
#Load the dataset with extracted values from google apis
df1 = pd.read_csv('merged.csv')
df1 = df1.drop(columns=['Unnamed: 0', 'decimalLatitude', 'decimalLongitude'])
df1.head()

     index  NDVI_raw  LandCover_Class  elevation_meters
0  1137708    7199.0               14                21
1  1602275    8229.0                8                58
2  1632979    8229.0                8                58
3  1670345    8229.0                8                58
4  1777636    8229.0                8                58

In [ ]:
# Merge the datasets together
df3 = pd.merge(final_df, df1, on='index')
df3.head()

,index,verbatimScientificName,stateProvince,individualCount,decimalLatitude,decimalLongitude,eventDate,avg_rad,cf_cvg,NDVI_raw,LandCover_Class,elevation_meters
0,0,Anarhynchus alexandrinus,Mannar,8.0,9.058512,79.85502,2021-01-06,0.66,5.0,3792.0,10,0
1,1,Columba livia,Colombo,31.0,6.927894,79.865005,2024-09-24,25.4,1.0,5692.0,13,12
2,2,Hirundo rustica,Colombo,10.0,6.866285,79.93144,2024-12-23,10.16,7.0,7045.0,13,5
3,3,Geokichla spiloptera,Matale,1.0,7.401229,80.69073,2024-09-13,1.13,1.0,9506.0,8,876
4,4,Himantopus himantopus,Puttalam,6.0,8.154166,79.736084,2024-11-28,0.79,2.0,NaN,11,2